::%Year%, %Month%, %Day%, %Hour%, %Minute%, %Second%, %Millisecond%
::%DateTime% is a number generated by concatenating all the variables above (16 figures)


reg copy "HKEY_CURRENT_USER\Control Panel\International" "HKEY_CURRENT_USER\Control Panel\InternationalCopy" /f>nul

reg add "HKEY_CURRENT_USER\Control Panel\International" /v sLongDate /t REG_SZ /d yyyy/MM/dd /f>nul
reg add "HKEY_CURRENT_USER\Control Panel\International" /v sShortDate /t REG_SZ /d yyyy/MM/dd /f>nul
reg add "HKEY_CURRENT_USER\Control Panel\International" /v sShortTime /t REG_SZ /d HH:mm:ss /f>nul
reg add "HKEY_CURRENT_USER\Control Panel\International" /v sTimeFormat /t REG_SZ /d HH:mm:ss /f>nul

set Year=%date:~0,4%
set Month=%date:~5,2%
set Day=%date:~8,2%

set Hour=%time:~0,2%
set Minute=%time:~3,2%
set Second=%time:~6,2%
set Millisecond=%time:~9,2%

set DateTime=%Year%%Month%%Day%%Hour%%Minute%%Second%%Millisecond%

reg copy "HKEY_CURRENT_USER\Control Panel\InternationalCopy" "HKEY_CURRENT_USER\Control Panel\International" /f>nul
reg delete "HKEY_CURRENT_USER\Control Panel\InternationalCopy" /f>nul
